/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiContext } from '@quote-calc-system/context';
import { CalcTestApplication200Response } from '@quote-calc-system/models';
import { CalcTestApplicationRequest } from '@quote-calc-system/models';

export type calcTestApplication = (params: { calcTestApplicationRequest: CalcTestApplicationRequest }, context: ApiContext) => Promise<CalcTestApplication200Response>;
