/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CalcTestApplication200Response } from '../models';
// @ts-ignore
import type { CalcTestApplicationRequest } from '../models';
/**
 * CalcApi - axios parameter creator
 * @export
 */
export const CalcApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ...
         * @summary 工数計算
         * @param {CalcTestApplicationRequest} calcTestApplicationRequest ...
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calcTestApplication: async (calcTestApplicationRequest: CalcTestApplicationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'calcTestApplicationRequest' is not null or undefined
            assertParamExists('calcTestApplication', 'calcTestApplicationRequest', calcTestApplicationRequest)
            const localVarPath = `/api/TEST/calc`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(calcTestApplicationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CalcApi - functional programming interface
 * @export
 */
export const CalcApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CalcApiAxiosParamCreator(configuration)
    return {
        /**
         * ...
         * @summary 工数計算
         * @param {CalcTestApplicationRequest} calcTestApplicationRequest ...
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async calcTestApplication(calcTestApplicationRequest: CalcTestApplicationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CalcTestApplication200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.calcTestApplication(calcTestApplicationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CalcApi.calcTestApplication']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CalcApi - factory interface
 * @export
 */
export const CalcApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CalcApiFp(configuration)
    return {
        /**
         * ...
         * @summary 工数計算
         * @param {CalcTestApplicationRequest} calcTestApplicationRequest ...
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        calcTestApplication(calcTestApplicationRequest: CalcTestApplicationRequest, options?: RawAxiosRequestConfig): AxiosPromise<CalcTestApplication200Response> {
            return localVarFp.calcTestApplication(calcTestApplicationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CalcApi - object-oriented interface
 * @export
 * @class CalcApi
 * @extends {BaseAPI}
 */
export class CalcApi extends BaseAPI {
    /**
     * ...
     * @summary 工数計算
     * @param {CalcTestApplicationRequest} calcTestApplicationRequest ...
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CalcApi
     */
    public calcTestApplication(calcTestApplicationRequest: CalcTestApplicationRequest, options?: RawAxiosRequestConfig) {
        return CalcApiFp(this.configuration).calcTestApplication(calcTestApplicationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

