/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ExportTestApplication200Response } from '../models';
// @ts-ignore
import type { ExportTestApplicationRequest } from '../models';
/**
 * ExportTestApi - axios parameter creator
 * @export
 */
export const ExportTestApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ...
         * @summary エクスポート
         * @param {ExportTestApplicationRequest} exportTestApplicationRequest ...
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportTestApplication: async (exportTestApplicationRequest: ExportTestApplicationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'exportTestApplicationRequest' is not null or undefined
            assertParamExists('exportTestApplication', 'exportTestApplicationRequest', exportTestApplicationRequest)
            const localVarPath = `/TEST/exportTest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exportTestApplicationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ExportTestApi - functional programming interface
 * @export
 */
export const ExportTestApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ExportTestApiAxiosParamCreator(configuration)
    return {
        /**
         * ...
         * @summary エクスポート
         * @param {ExportTestApplicationRequest} exportTestApplicationRequest ...
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportTestApplication(exportTestApplicationRequest: ExportTestApplicationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExportTestApplication200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportTestApplication(exportTestApplicationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ExportTestApi.exportTestApplication']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ExportTestApi - factory interface
 * @export
 */
export const ExportTestApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ExportTestApiFp(configuration)
    return {
        /**
         * ...
         * @summary エクスポート
         * @param {ExportTestApplicationRequest} exportTestApplicationRequest ...
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportTestApplication(exportTestApplicationRequest: ExportTestApplicationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExportTestApplication200Response> {
            return localVarFp.exportTestApplication(exportTestApplicationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ExportTestApi - object-oriented interface
 * @export
 * @class ExportTestApi
 * @extends {BaseAPI}
 */
export class ExportTestApi extends BaseAPI {
    /**
     * ...
     * @summary エクスポート
     * @param {ExportTestApplicationRequest} exportTestApplicationRequest ...
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ExportTestApi
     */
    public exportTestApplication(exportTestApplicationRequest: ExportTestApplicationRequest, options?: RawAxiosRequestConfig) {
        return ExportTestApiFp(this.configuration).exportTestApplication(exportTestApplicationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

