openapi: 3.0.0
info:
  title: 見積算出システム API
  description: ...
  version: 1.0.0
paths:
  # /TEST/test:
  #   $ref: ./TEST.yml#/paths/~1TEST~1test
  /TEST/calc:
    $ref: ./TEST.yml#/paths/~1TEST~1calc
  /TEST/export:
    $ref: ./TEST.yml#/paths/~1TEST~1export
  /TEST/import:
    $ref: ./TEST.yml#/paths/~1TEST~1import
