openapi: 3.0.0
info:
  title: TEST API
  version: 1.0.0
tags:
  - name: test
    description: ...
  - name: calc
    description: 工数計算関連
paths:
  /TEST/calc:
    post:
      summary: 工数計算
      tags:
        - calc
      operationId: calcTestApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalcTestApplicationRequest"
      responses:
        "200":
          description: ...
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalcTestApplication200Response"

  /TEST/export:
    post:
      summary: エクスポート
      tags:
        - export
      operationId: exportApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExportApplicationRequest"
      responses:
        "200":
          description: ...
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExportApplication200Response"

  /TEST/import:
    post:
      summary: インポート
      tags:
        - import
      operationId: importApplication
      description: ...
      requestBody:
        description: ...
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Excel file
      responses:
        "200":
          description: ...
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImportApplication200Response"                 

  /TEST/ping:
    get:
      tags:
        - test
      summary: 接続確認用
      operationId: ping
      responses:
        '200':
          description: 正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: pong

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CalcTestApplicationRequest:
      description: 工数計算リクエスト
      type: object
      properties:
        projectName:
          type: string
        autoProductivity:
          type: boolean
        autoProcessRatios:
          type: boolean
        productivityFPPerMonth:
          type: number
        projectType:
          type: string
        ipaValueType:
          type: string
        dataFunctions:
          type: array
          items:
            type: object
            properties:
              updateType:
                type: string
        transactionFunctions:
          type: array
          items:
            type: object
            properties:
              externalInput:
                type: number
              externalOutput:
                type: number
              externalInquiry:
                type: number
        processRatios:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
      # required:
      #   - projectName
      #   - productivityFPPerMonth
    CalcTestApplication200Response:
      description: 工数計算レスポンス
      type: object
      properties:
        projectName:
          type: string
        productivityFPPerMonth:
          type: number
        totalFP:
          type: number
        totalManMonths:
          type: number
        standardDurationMonths:
          type: number  
        dataFunctions:
          type: array
          items:
            type: object
            properties:
              fpValue:
                type: number
        transactionFunctions:
          type: array
          items:
            type: object
            properties:
              fpValue:
                type: number
        processRatios:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number        
        processFPs:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        processManMonths:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        processDurations:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        errorMessages:
          type: array
          items:
            type: string
    ExportApplicationRequest:
      description: エクスポートリクエスト
      type: object
      properties:
        projectName:
          type: string
        productivityFPPerMonth:
          type: number
        projectType:
          type: string
        ipaValueType:
          type: string
        totalFP:
          type: number
        totalManMonths:
          type: number
        standardDurationMonths:
          type: number
        processRatios:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        processManMonths:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        processDurations:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number  
        importFile:
          type: object
          properties:
            name:
              type: string
              description: ファイル名
            content:
              type: string
              format: byte
              description: ファイル内容
        exportFile:
          type: object
          properties:
            name:
              type: string
              description: ファイル名
            content:
              type: string
              format: byte
              description: ファイル内容
        dataFunctions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              updateType:
                type: string
              fpValue:
                type: number
              remarks:
                type: string
        transactionFunctions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              externalInput:
                type: number
              externalOutput:
                type: number
              externalInquiry:
                type: number
              fpValue:
                type: number
              remarks:
                type: string
    ExportApplication200Response:
      description: エクスポートレスポンス
      type: object
      properties:
        dataFunctions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              updateType:
                type: string
              fpValue:
                type: number
              remarks:
                type: string
              selected:
                type: boolean
        exportFile:
          type: object
          properties:
            name:
              type: string
              description: ファイル名
            content:
              type: string
              description: ファイル内容
        errorMessages:
          type: array
          items:
            type: string
    ImportApplication200Response:
      description: インポートレスポンス
      type: object
      properties:
        projectName:
          type: string
        productivityFPPerMonth:
          type: number
        projectType:
          type: string
        ipaValueType:
          type: string
        totalFP:
          type: number
        totalManMonths:
          type: number
        standardDurationMonths:
          type: number
        processRatios:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        processManMonths:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        processDurations:
          type: object
          properties:
            basicDesign:
              type: number
            detailedDesign:
              type: number
            implementation:
              type: number
            integrationTest:
              type: number
            systemTest:
              type: number
        dataFunctions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              updateType:
                type: string
              fpValue:
                type: number
              remarks:
                type: string
              selected:
                type: boolean
        transactionFunctions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              externalInput:
                type: number
              externalOutput:
                type: number
              externalInquiry:
                type: number
              fpValue:
                type: number
              remarks:
                type: string
        errorMessages:
          type: array
          items:
            type: string

