/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiContext } from '@quote-calc-system/context';
import { ApiTESTTestGet200ResponseInner } from '@quote-calc-system/models';

export type apiTESTTestGet = (context: ApiContext) => Promise<Array<ApiTESTTestGet200ResponseInner>>;
export type apiTESTTestPost = (params: { apiTESTTestGet200ResponseInner: ApiTESTTestGet200ResponseInner }, context: ApiContext) => Promise<ApiTESTTestGet200ResponseInner>;
