/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import axios from './axios';

import { CalcApiFactory } from './apis/calc-api';
import { TestApiFactory } from './apis/test-api';

export const calcApi = CalcApiFactory(undefined, undefined, axios);
export const testApi = TestApiFactory(undefined, undefined, axios);

