/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseDataFunctionsInner } from './calc-test-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessRatios } from './calc-test-application200-response-process-ratios';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseTransactionFunctionsInner } from './calc-test-application200-response-transaction-functions-inner';

/**
 * 工数計算リクエスト
 * @export
 * @interface CalcTestApplicationRequest
 */
export interface CalcTestApplicationRequest {
    /**
     * 案件名
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'projectName'?: string;
    /**
     * 生産性自動計算フラグ
     * @type {boolean}
     * @memberof CalcTestApplicationRequest
     */
    'autoProductivity'?: boolean;
    /**
     * 生産性（FP/月）
     * @type {number}
     * @memberof CalcTestApplicationRequest
     */
    'productivityFPPerMonth'?: number;
    /**
     * 案件種別
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'projectType'?: CalcTestApplicationRequestProjectTypeEnum;
    /**
     * 使用するIPA代表値
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'ipaValueType'?: CalcTestApplicationRequestIpaValueTypeEnum;
    /**
     * 開発工程比率自動入力フラグ
     * @type {boolean}
     * @memberof CalcTestApplicationRequest
     */
    'autoProcessRatios'?: boolean;
    /**
     * :データファンクション情報
     * @type {Array<CalcTestApplication200ResponseDataFunctionsInner>}
     * @memberof CalcTestApplicationRequest
     */
    'dataFunctions'?: Array<CalcTestApplication200ResponseDataFunctionsInner>;
    /**
     * トランザクションファンクション情報
     * @type {Array<CalcTestApplication200ResponseTransactionFunctionsInner>}
     * @memberof CalcTestApplicationRequest
     */
    'transactionFunctions'?: Array<CalcTestApplication200ResponseTransactionFunctionsInner>;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof CalcTestApplicationRequest
     */
    'processRatios'?: CalcTestApplication200ResponseProcessRatios;
}

export const CalcTestApplicationRequestProjectTypeEnum = {
    NEW: 'N',
    ENHANCEMENT: 'E',
    REDEVELOPMENT: 'R'
} as const;

export type CalcTestApplicationRequestProjectTypeEnum = typeof CalcTestApplicationRequestProjectTypeEnum[keyof typeof CalcTestApplicationRequestProjectTypeEnum];
export const CalcTestApplicationRequestIpaValueTypeEnum = {
    MEDIAN: 'M',
    AVERAGE: 'A'
} as const;

export type CalcTestApplicationRequestIpaValueTypeEnum = typeof CalcTestApplicationRequestIpaValueTypeEnum[keyof typeof CalcTestApplicationRequestIpaValueTypeEnum];

