/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CalcTestApplication200ResponseTransactionFunctionsInner
 */
export interface CalcTestApplication200ResponseTransactionFunctionsInner {
    /**
     * 
     * @type {boolean}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'selected'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'externalInput'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'externalOutput'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'externalInquiry'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'fpValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplication200ResponseTransactionFunctionsInner
     */
    'remarks'?: string;
}
