/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CalcTestApplicationRequestProcessRatios
 */
export interface CalcTestApplicationRequestProcessRatios {
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequestProcessRatios
     */
    'basicDesign'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequestProcessRatios
     */
    'detailedDesign'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequestProcessRatios
     */
    'implementation'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequestProcessRatios
     */
    'integrationTest'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequestProcessRatios
     */
    'systemTest'?: number;
}
