/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseDataFunctionsInner } from './calc-test-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessRatios } from './calc-test-application200-response-process-ratios';

/**
 * 工数計算レスポンス
 * @export
 * @interface CalcTestApplication200Response
 */
export interface CalcTestApplication200Response {
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplication200Response
     */
    'projectName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200Response
     */
    'productivityFPPerMonth'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200Response
     */
    'totalFP'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200Response
     */
    'totalManMonths'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplication200Response
     */
    'standardDurationMonths'?: number;
    /**
     * 
     * @type {Array<CalcTestApplication200ResponseDataFunctionsInner>}
     * @memberof CalcTestApplication200Response
     */
    'dataFunctions'?: Array<CalcTestApplication200ResponseDataFunctionsInner>;
    /**
     * 
     * @type {Array<CalcTestApplication200ResponseDataFunctionsInner>}
     * @memberof CalcTestApplication200Response
     */
    'transactionFunctions'?: Array<CalcTestApplication200ResponseDataFunctionsInner>;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof CalcTestApplication200Response
     */
    'processRatios'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof CalcTestApplication200Response
     */
    'processManMonths'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof CalcTestApplication200Response
     */
    'processDurations'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {Array<string>}
     * @memberof CalcTestApplication200Response
     */
    'errorMessages'?: Array<string>;
}
