/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { DataFunctionUpdateType } from './data-function-update-type';

/**
 * 
 * @export
 * @interface CalcTestApplication200ResponseDataFunctionsInner
 */
export interface CalcTestApplication200ResponseDataFunctionsInner {
    /**
     * 名称
     * @type {string}
     * @memberof CalcTestApplication200ResponseDataFunctionsInner
     */
    'name'?: string;
    /**
     * 
     * @type {DataFunctionUpdateType}
     * @memberof CalcTestApplication200ResponseDataFunctionsInner
     */
    'updateType'?: DataFunctionUpdateType;
    /**
     * FP
     * @type {number}
     * @memberof CalcTestApplication200ResponseDataFunctionsInner
     */
    'fpValue'?: number;
    /**
     * 備考
     * @type {string}
     * @memberof CalcTestApplication200ResponseDataFunctionsInner
     */
    'remarks'?: string;
    /**
     * 選択フラグ
     * @type {boolean}
     * @memberof CalcTestApplication200ResponseDataFunctionsInner
     */
    'selected'?: boolean;
}


