/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 開発工程標準工期（月）
 * @export
 * @interface CalcTestApplication200ResponseProcessDurations
 */
export interface CalcTestApplication200ResponseProcessDurations {
    /**
     * 基本設計
     * @type {number}
     * @memberof CalcTestApplication200ResponseProcessDurations
     */
    'basicDesign'?: number;
    /**
     * 詳細設計
     * @type {number}
     * @memberof CalcTestApplication200ResponseProcessDurations
     */
    'detailedDesign'?: number;
    /**
     * 製造
     * @type {number}
     * @memberof CalcTestApplication200ResponseProcessDurations
     */
    'implementation'?: number;
    /**
     * 結合テスト
     * @type {number}
     * @memberof CalcTestApplication200ResponseProcessDurations
     */
    'integrationTest'?: number;
    /**
     * 総合テスト
     * @type {number}
     * @memberof CalcTestApplication200ResponseProcessDurations
     */
    'systemTest'?: number;
}
