/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseDataFunctionsInner } from './calc-test-application200-response-data-functions-inner';

/**
 * 工数計算リクエスト
 * @export
 * @interface CalcTestApplicationRequest
 */
export interface CalcTestApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'projectName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequest
     */
    'productivityFPPerMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'projectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'ipaValueType'?: string;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequest
     */
    'totalFP'?: number;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequest
     */
    'manMonth'?: number;
    /**
     * 
     * @type {Array<CalcTestApplication200ResponseDataFunctionsInner>}
     * @memberof CalcTestApplicationRequest
     */
    'dataFunctions'?: Array<CalcTestApplication200ResponseDataFunctionsInner>;
}
