/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessRatios } from './calc-test-application200-response-process-ratios';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplicationRequestDataFunctionsInner } from './calc-test-application-request-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplicationRequestTransactionFunctionsInner } from './calc-test-application-request-transaction-functions-inner';

/**
 * 工数計算リクエスト
 * @export
 * @interface CalcTestApplicationRequest
 */
export interface CalcTestApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'projectName'?: string;
    /**
     * 
     * @type {number}
     * @memberof CalcTestApplicationRequest
     */
    'productivityFPPerMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'projectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof CalcTestApplicationRequest
     */
    'ipaValueType'?: string;
    /**
     * 
     * @type {Array<CalcTestApplicationRequestDataFunctionsInner>}
     * @memberof CalcTestApplicationRequest
     */
    'dataFunctions'?: Array<CalcTestApplicationRequestDataFunctionsInner>;
    /**
     * 
     * @type {Array<CalcTestApplicationRequestTransactionFunctionsInner>}
     * @memberof CalcTestApplicationRequest
     */
    'transactionFunctions'?: Array<CalcTestApplicationRequestTransactionFunctionsInner>;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof CalcTestApplicationRequest
     */
    'processRatios'?: CalcTestApplication200ResponseProcessRatios;
}
