/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @enum {string}
 */

export const DataFunctionUpdateType = {
    ILF: 'I',
    EIF: 'E'
} as const;

export type DataFunctionUpdateType = typeof DataFunctionUpdateType[keyof typeof DataFunctionUpdateType];

