/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExportTestApplication200ResponseDataFunctionsInner } from './export-test-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportTestApplicationRequestImportFile } from './export-test-application-request-import-file';

/**
 * エクスポートリクエスト
 * @export
 * @interface ExportTestApplicationRequest
 */
export interface ExportTestApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof ExportTestApplicationRequest
     */
    'projectName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExportTestApplicationRequest
     */
    'productivityFPPerMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExportTestApplicationRequest
     */
    'projectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportTestApplicationRequest
     */
    'ipaValueType'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExportTestApplicationRequest
     */
    'totalFP'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExportTestApplicationRequest
     */
    'totalManMonths'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExportTestApplicationRequest
     */
    'standardDurationMonths'?: number;
    /**
     * 
     * @type {ExportTestApplicationRequestImportFile}
     * @memberof ExportTestApplicationRequest
     */
    'importFile'?: ExportTestApplicationRequestImportFile;
    /**
     * 
     * @type {ExportTestApplicationRequestImportFile}
     * @memberof ExportTestApplicationRequest
     */
    'exportFile'?: ExportTestApplicationRequestImportFile;
    /**
     * 
     * @type {Array<ExportTestApplication200ResponseDataFunctionsInner>}
     * @memberof ExportTestApplicationRequest
     */
    'dataFunctions'?: Array<ExportTestApplication200ResponseDataFunctionsInner>;
}
