/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplication200ResponseDataFunctionsInner } from './export-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplication200ResponseExportFile } from './export-application200-response-export-file';

/**
 * エクスポートレスポンス
 * @export
 * @interface ExportApplication200Response
 */
export interface ExportApplication200Response {
    /**
     * 
     * @type {Array<ExportApplication200ResponseDataFunctionsInner>}
     * @memberof ExportApplication200Response
     */
    'dataFunctions'?: Array<ExportApplication200ResponseDataFunctionsInner>;
    /**
     * 
     * @type {ExportApplication200ResponseExportFile}
     * @memberof ExportApplication200Response
     */
    'exportFile'?: ExportApplication200ResponseExportFile;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExportApplication200Response
     */
    'errorMessages'?: Array<string>;
}
