/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ExportApplication200ResponseExportFile
 */
export interface ExportApplication200ResponseExportFile {
    /**
     * ファイル名
     * @type {string}
     * @memberof ExportApplication200ResponseExportFile
     */
    'name'?: string;
    /**
     * ファイル内容
     * @type {string}
     * @memberof ExportApplication200ResponseExportFile
     */
    'content'?: string;
}
