/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseDataFunctionsInner } from './calc-test-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportTestApplication200ResponseExportFile } from './export-test-application200-response-export-file';

/**
 * エクスポートレスポンス
 * @export
 * @interface ExportTestApplication200Response
 */
export interface ExportTestApplication200Response {
    /**
     * 
     * @type {Array<CalcTestApplication200ResponseDataFunctionsInner>}
     * @memberof ExportTestApplication200Response
     */
    'dataFunctions'?: Array<CalcTestApplication200ResponseDataFunctionsInner>;
    /**
     * 
     * @type {ExportTestApplication200ResponseExportFile}
     * @memberof ExportTestApplication200Response
     */
    'exportFile'?: ExportTestApplication200ResponseExportFile;
}
