/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseDataFunctionsInner } from './calc-test-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessRatios } from './calc-test-application200-response-process-ratios';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseTransactionFunctionsInner } from './calc-test-application200-response-transaction-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplicationRequestImportFile } from './export-application-request-import-file';

/**
 * エクスポートリクエスト
 * @export
 * @interface ExportApplicationRequest
 */
export interface ExportApplicationRequest {
    /**
     * 
     * @type {string}
     * @memberof ExportApplicationRequest
     */
    'projectName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'productivityFPPerMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof ExportApplicationRequest
     */
    'projectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportApplicationRequest
     */
    'ipaValueType'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'totalFP'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'totalManMonths'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'standardDurationMonths'?: number;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ExportApplicationRequest
     */
    'processRatios'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ExportApplicationRequest
     */
    'processManMonths'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ExportApplicationRequest
     */
    'processDurations'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {ExportApplicationRequestImportFile}
     * @memberof ExportApplicationRequest
     */
    'importFile'?: ExportApplicationRequestImportFile;
    /**
     * 
     * @type {ExportApplicationRequestImportFile}
     * @memberof ExportApplicationRequest
     */
    'exportFile'?: ExportApplicationRequestImportFile;
    /**
     * 
     * @type {Array<CalcTestApplication200ResponseDataFunctionsInner>}
     * @memberof ExportApplicationRequest
     */
    'dataFunctions'?: Array<CalcTestApplication200ResponseDataFunctionsInner>;
    /**
     * 
     * @type {Array<CalcTestApplication200ResponseTransactionFunctionsInner>}
     * @memberof ExportApplicationRequest
     */
    'transactionFunctions'?: Array<CalcTestApplication200ResponseTransactionFunctionsInner>;
}
