/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessDurations } from './calc-test-application200-response-process-durations';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessFPs } from './calc-test-application200-response-process-fps';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessManMonths } from './calc-test-application200-response-process-man-months';
// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessRatios } from './calc-test-application200-response-process-ratios';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplicationRequestDataFunctionsInner } from './export-application-request-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplicationRequestExportFile } from './export-application-request-export-file';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplicationRequestTransactionFunctionsInner } from './export-application-request-transaction-functions-inner';

/**
 * エクスポートリクエスト
 * @export
 * @interface ExportApplicationRequest
 */
export interface ExportApplicationRequest {
    /**
     * 案件名
     * @type {string}
     * @memberof ExportApplicationRequest
     */
    'projectName'?: string;
    /**
     * 生産性（FP/月）
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'productivityFPPerMonth'?: number;
    /**
     * 案件種別
     * @type {string}
     * @memberof ExportApplicationRequest
     */
    'projectType'?: ExportApplicationRequestProjectTypeEnum;
    /**
     * 使用するIPA代表値
     * @type {string}
     * @memberof ExportApplicationRequest
     */
    'ipaValueType'?: ExportApplicationRequestIpaValueTypeEnum;
    /**
     * 総FP
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'totalFP'?: number;
    /**
     * 工数（人月）
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'totalManMonths'?: number;
    /**
     * 標準工期（月）
     * @type {number}
     * @memberof ExportApplicationRequest
     */
    'standardDurationMonths'?: number;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ExportApplicationRequest
     */
    'processRatios'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessFPs}
     * @memberof ExportApplicationRequest
     */
    'processFPs'?: CalcTestApplication200ResponseProcessFPs;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessManMonths}
     * @memberof ExportApplicationRequest
     */
    'processManMonths'?: CalcTestApplication200ResponseProcessManMonths;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessDurations}
     * @memberof ExportApplicationRequest
     */
    'processDurations'?: CalcTestApplication200ResponseProcessDurations;
    /**
     * 
     * @type {ExportApplicationRequestExportFile}
     * @memberof ExportApplicationRequest
     */
    'exportFile'?: ExportApplicationRequestExportFile;
    /**
     * 
     * @type {Array<ExportApplicationRequestDataFunctionsInner>}
     * @memberof ExportApplicationRequest
     */
    'dataFunctions'?: Array<ExportApplicationRequestDataFunctionsInner>;
    /**
     * 
     * @type {Array<ExportApplicationRequestTransactionFunctionsInner>}
     * @memberof ExportApplicationRequest
     */
    'transactionFunctions'?: Array<ExportApplicationRequestTransactionFunctionsInner>;
}

export const ExportApplicationRequestProjectTypeEnum = {
    NEW: 'N',
    ENHANCEMENT: 'E',
    REDEVELOPMENT: 'R'
} as const;

export type ExportApplicationRequestProjectTypeEnum = typeof ExportApplicationRequestProjectTypeEnum[keyof typeof ExportApplicationRequestProjectTypeEnum];
export const ExportApplicationRequestIpaValueTypeEnum = {
    MEDIAN: 'M',
    AVERAGE: 'A'
} as const;

export type ExportApplicationRequestIpaValueTypeEnum = typeof ExportApplicationRequestIpaValueTypeEnum[keyof typeof ExportApplicationRequestIpaValueTypeEnum];

