/* tslint:disable */
/* eslint-disable */
/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CalcTestApplication200ResponseProcessRatios } from './calc-test-application200-response-process-ratios';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplication200ResponseDataFunctionsInner } from './export-application200-response-data-functions-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ExportApplicationRequestTransactionFunctionsInner } from './export-application-request-transaction-functions-inner';

/**
 * インポートレスポンス
 * @export
 * @interface ImportApplication200Response
 */
export interface ImportApplication200Response {
    /**
     * 
     * @type {string}
     * @memberof ImportApplication200Response
     */
    'projectName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ImportApplication200Response
     */
    'productivityFPPerMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof ImportApplication200Response
     */
    'projectType'?: string;
    /**
     * 
     * @type {string}
     * @memberof ImportApplication200Response
     */
    'ipaValueType'?: string;
    /**
     * 
     * @type {number}
     * @memberof ImportApplication200Response
     */
    'totalFP'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportApplication200Response
     */
    'totalManMonths'?: number;
    /**
     * 
     * @type {number}
     * @memberof ImportApplication200Response
     */
    'standardDurationMonths'?: number;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ImportApplication200Response
     */
    'processRatios'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ImportApplication200Response
     */
    'processManMonths'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {CalcTestApplication200ResponseProcessRatios}
     * @memberof ImportApplication200Response
     */
    'processDurations'?: CalcTestApplication200ResponseProcessRatios;
    /**
     * 
     * @type {Array<ExportApplication200ResponseDataFunctionsInner>}
     * @memberof ImportApplication200Response
     */
    'dataFunctions'?: Array<ExportApplication200ResponseDataFunctionsInner>;
    /**
     * 
     * @type {Array<ExportApplicationRequestTransactionFunctionsInner>}
     * @memberof ImportApplication200Response
     */
    'transactionFunctions'?: Array<ExportApplicationRequestTransactionFunctionsInner>;
}
