/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type RequestFile = File;
import { ApiContext } from '@quote-calc-system/context';
import { ImportApplication200Response } from '@quote-calc-system/models';

export type importApplication = (params: { file: RequestFile }, context: ApiContext) => Promise<ImportApplication200Response>;
