/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CalcTestApplicationRequestProcessRatios {
    'basicDesign'?: number;
    'detailedDesign'?: number;
    'implementation'?: number;
    'integrationTest'?: number;
    'systemTest'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "basicDesign",
            "baseName": "basicDesign",
            "type": "number"
        },
        {
            "name": "detailedDesign",
            "baseName": "detailedDesign",
            "type": "number"
        },
        {
            "name": "implementation",
            "baseName": "implementation",
            "type": "number"
        },
        {
            "name": "integrationTest",
            "baseName": "integrationTest",
            "type": "number"
        },
        {
            "name": "systemTest",
            "baseName": "systemTest",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequestProcessRatios.attributeTypeMap;
    }
}

