/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CalcTestApplication200ResponseDataFunctionsInner {
    'fpValue'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fpValue",
            "baseName": "fpValue",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplication200ResponseDataFunctionsInner.attributeTypeMap;
    }
}

