/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CalcTestApplicationRequestTransactionFunctionsInner {
    'selected'?: boolean;
    'name'?: string;
    'externalInput'?: number;
    'externalOutput'?: number;
    'externalInquiry'?: number;
    'fpValue'?: number;
    'remarks'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "selected",
            "baseName": "selected",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "externalInput",
            "baseName": "externalInput",
            "type": "number"
        },
        {
            "name": "externalOutput",
            "baseName": "externalOutput",
            "type": "number"
        },
        {
            "name": "externalInquiry",
            "baseName": "externalInquiry",
            "type": "number"
        },
        {
            "name": "fpValue",
            "baseName": "fpValue",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequestTransactionFunctionsInner.attributeTypeMap;
    }
}

