/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CalcTestApplicationRequestDataFunctionsInner {
    /**
    * 名称
    */
    'name'?: string;
    'updateType'?: CalcTestApplicationRequestDataFunctionsInner.UpdateTypeEnum;
    /**
    * FP
    */
    'fpValue'?: number;
    /**
    * 備考
    */
    'remarks'?: string;
    /**
    * 選択フラグ
    */
    'selected'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "updateType",
            "baseName": "updateType",
            "type": "CalcTestApplicationRequestDataFunctionsInner.UpdateTypeEnum"
        },
        {
            "name": "fpValue",
            "baseName": "fpValue",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        },
        {
            "name": "selected",
            "baseName": "selected",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequestDataFunctionsInner.attributeTypeMap;
    }
}

export namespace CalcTestApplicationRequestDataFunctionsInner {
    export enum UpdateTypeEnum {
        ILF = <any> 'I',
        EIF = <any> 'E'
    }
}
