/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CalcTestApplicationRequestDataFunctionsInner } from './calcTestApplicationRequestDataFunctionsInner';
import { CalcTestApplicationRequestProcessRatios } from './calcTestApplicationRequestProcessRatios';
import { CalcTestApplicationRequestTransactionFunctionsInner } from './calcTestApplicationRequestTransactionFunctionsInner';

/**
* 工数計算リクエスト
*/
export class CalcTestApplicationRequest {
    /**
    * 案件名
    */
    'projectName'?: string;
    /**
    * 生産性自動計算フラグ
    */
    'autoProductivity'?: boolean;
    /**
    * 生産性（FP/月）
    */
    'productivityFPPerMonth'?: number;
    /**
    * 案件種別
    */
    'projectType'?: CalcTestApplicationRequest.ProjectTypeEnum;
    /**
    * 使用するIPA代表値
    */
    'ipaValueType'?: CalcTestApplicationRequest.IpaValueTypeEnum;
    /**
    * 開発工程比率自動入力フラグ
    */
    'autoProcessRatios'?: boolean;
    /**
    * :データファンクション情報
    */
    'dataFunctions'?: Array<CalcTestApplicationRequestDataFunctionsInner>;
    /**
    * トランザクションファンクション情報
    */
    'transactionFunctions'?: Array<CalcTestApplicationRequestTransactionFunctionsInner>;
    'processRatios'?: CalcTestApplicationRequestProcessRatios;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "autoProductivity",
            "baseName": "autoProductivity",
            "type": "boolean"
        },
        {
            "name": "productivityFPPerMonth",
            "baseName": "productivityFPPerMonth",
            "type": "number"
        },
        {
            "name": "projectType",
            "baseName": "projectType",
            "type": "CalcTestApplicationRequest.ProjectTypeEnum"
        },
        {
            "name": "ipaValueType",
            "baseName": "ipaValueType",
            "type": "CalcTestApplicationRequest.IpaValueTypeEnum"
        },
        {
            "name": "autoProcessRatios",
            "baseName": "autoProcessRatios",
            "type": "boolean"
        },
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<CalcTestApplicationRequestDataFunctionsInner>"
        },
        {
            "name": "transactionFunctions",
            "baseName": "transactionFunctions",
            "type": "Array<CalcTestApplicationRequestTransactionFunctionsInner>"
        },
        {
            "name": "processRatios",
            "baseName": "processRatios",
            "type": "CalcTestApplicationRequestProcessRatios"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequest.attributeTypeMap;
    }
}

export namespace CalcTestApplicationRequest {
    export enum ProjectTypeEnum {
        NEW = <any> 'N',
        ENHANCEMENT = <any> 'E',
        REDEVELOPMENT = <any> 'R'
    }
    export enum IpaValueTypeEnum {
        MEDIAN = <any> 'M',
        AVERAGE = <any> 'A'
    }
}
