/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class CalcTestApplicationRequestTransactionFunctionsInner {
    /**
    * 名称
    */
    'name'?: string;
    /**
    * 外部入力
    */
    'externalInput'?: number;
    /**
    * 外部出力
    */
    'externalOutput'?: number;
    /**
    * 外部照会
    */
    'externalInquiry'?: number;
    /**
    * FP
    */
    'fpValue'?: number;
    /**
    * 備考
    */
    'remarks'?: string;
    /**
    * 選択フラグ
    */
    'selected'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "externalInput",
            "baseName": "externalInput",
            "type": "number"
        },
        {
            "name": "externalOutput",
            "baseName": "externalOutput",
            "type": "number"
        },
        {
            "name": "externalInquiry",
            "baseName": "externalInquiry",
            "type": "number"
        },
        {
            "name": "fpValue",
            "baseName": "fpValue",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        },
        {
            "name": "selected",
            "baseName": "selected",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequestTransactionFunctionsInner.attributeTypeMap;
    }
}

