/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ByteBuffer } from './byteBuffer';

export class CalcTestApplicationRequestImportFile {
    /**
    * ファイル名
    */
    'name'?: string;
    /**
    * ファイル内容
    */
    'content'?: ByteBuffer;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "ByteBuffer"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequestImportFile.attributeTypeMap;
    }
}

