/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CalcTestApplicationRequestDataFunctionsInner } from './calcTestApplicationRequestDataFunctionsInner';
import { CalcTestApplicationRequestProcessRatios } from './calcTestApplicationRequestProcessRatios';
import { CalcTestApplicationRequestTransactionFunctionsInner } from './calcTestApplicationRequestTransactionFunctionsInner';

/**
* 工数計算リクエスト
*/
export class CalcTestApplicationRequest {
    'projectName'?: string;
    'productivityFPPerMonth'?: number;
    'projectType'?: string;
    'ipaValueType'?: string;
    'dataFunctions'?: Array<CalcTestApplicationRequestDataFunctionsInner>;
    'transactionFunctions'?: Array<CalcTestApplicationRequestTransactionFunctionsInner>;
    'processRatios'?: CalcTestApplicationRequestProcessRatios;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "productivityFPPerMonth",
            "baseName": "productivityFPPerMonth",
            "type": "number"
        },
        {
            "name": "projectType",
            "baseName": "projectType",
            "type": "string"
        },
        {
            "name": "ipaValueType",
            "baseName": "ipaValueType",
            "type": "string"
        },
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<CalcTestApplicationRequestDataFunctionsInner>"
        },
        {
            "name": "transactionFunctions",
            "baseName": "transactionFunctions",
            "type": "Array<CalcTestApplicationRequestTransactionFunctionsInner>"
        },
        {
            "name": "processRatios",
            "baseName": "processRatios",
            "type": "CalcTestApplicationRequestProcessRatios"
        }    ];

    static getAttributeTypeMap() {
        return CalcTestApplicationRequest.attributeTypeMap;
    }
}

