/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ExportApplicationRequestDataFunctionsInner {
    'name'?: string;
    'updateType'?: string;
    'fpValue'?: number;
    'remarks'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "updateType",
            "baseName": "updateType",
            "type": "string"
        },
        {
            "name": "fpValue",
            "baseName": "fpValue",
            "type": "number"
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExportApplicationRequestDataFunctionsInner.attributeTypeMap;
    }
}

