/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExportTestApplication200ResponseExportFile } from './exportTestApplication200ResponseExportFile';
import { ExportTestApplicationRequestDataFunctionsInner } from './exportTestApplicationRequestDataFunctionsInner';

/**
* エクスポートレスポンス
*/
export class ExportTestApplication200Response {
    'dataFunctions'?: Array<ExportTestApplicationRequestDataFunctionsInner>;
    'exportFile'?: ExportTestApplication200ResponseExportFile;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<ExportTestApplicationRequestDataFunctionsInner>"
        },
        {
            "name": "exportFile",
            "baseName": "exportFile",
            "type": "ExportTestApplication200ResponseExportFile"
        }    ];

    static getAttributeTypeMap() {
        return ExportTestApplication200Response.attributeTypeMap;
    }
}

