/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CalcTestApplication200ResponseDisplayedProcessRatios } from './calcTestApplication200ResponseDisplayedProcessRatios';
import { CalcTestApplication200ResponseProcessDurations } from './calcTestApplication200ResponseProcessDurations';
import { CalcTestApplication200ResponseProcessFPs } from './calcTestApplication200ResponseProcessFPs';
import { CalcTestApplication200ResponseProcessManMonths } from './calcTestApplication200ResponseProcessManMonths';
import { ExportApplicationRequestDataFunctionsInner } from './exportApplicationRequestDataFunctionsInner';
import { ExportApplicationRequestExportFile } from './exportApplicationRequestExportFile';
import { ExportApplicationRequestTransactionFunctionsInner } from './exportApplicationRequestTransactionFunctionsInner';

/**
* エクスポートリクエスト
*/
export class ExportApplicationRequest {
    /**
    * 案件名
    */
    'projectName'?: string;
    /**
    * 生産性（FP/月）
    */
    'productivityFPPerMonth'?: number;
    /**
    * 案件種別
    */
    'projectType'?: ExportApplicationRequest.ProjectTypeEnum;
    /**
    * 使用するIPA代表値
    */
    'ipaValueType'?: ExportApplicationRequest.IpaValueTypeEnum;
    /**
    * 総FP
    */
    'totalFP'?: number;
    /**
    * 工数（人月）
    */
    'totalManMonths'?: number;
    /**
    * 標準工期（月）
    */
    'standardDurationMonths'?: number;
    'displayedProcessRatios'?: CalcTestApplication200ResponseDisplayedProcessRatios;
    'processFPs'?: CalcTestApplication200ResponseProcessFPs;
    'processManMonths'?: CalcTestApplication200ResponseProcessManMonths;
    'processDurations'?: CalcTestApplication200ResponseProcessDurations;
    'exportFile'?: ExportApplicationRequestExportFile;
    'dataFunctions'?: Array<ExportApplicationRequestDataFunctionsInner>;
    'transactionFunctions'?: Array<ExportApplicationRequestTransactionFunctionsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "productivityFPPerMonth",
            "baseName": "productivityFPPerMonth",
            "type": "number"
        },
        {
            "name": "projectType",
            "baseName": "projectType",
            "type": "ExportApplicationRequest.ProjectTypeEnum"
        },
        {
            "name": "ipaValueType",
            "baseName": "ipaValueType",
            "type": "ExportApplicationRequest.IpaValueTypeEnum"
        },
        {
            "name": "totalFP",
            "baseName": "totalFP",
            "type": "number"
        },
        {
            "name": "totalManMonths",
            "baseName": "totalManMonths",
            "type": "number"
        },
        {
            "name": "standardDurationMonths",
            "baseName": "standardDurationMonths",
            "type": "number"
        },
        {
            "name": "displayedProcessRatios",
            "baseName": "displayedProcessRatios",
            "type": "CalcTestApplication200ResponseDisplayedProcessRatios"
        },
        {
            "name": "processFPs",
            "baseName": "processFPs",
            "type": "CalcTestApplication200ResponseProcessFPs"
        },
        {
            "name": "processManMonths",
            "baseName": "processManMonths",
            "type": "CalcTestApplication200ResponseProcessManMonths"
        },
        {
            "name": "processDurations",
            "baseName": "processDurations",
            "type": "CalcTestApplication200ResponseProcessDurations"
        },
        {
            "name": "exportFile",
            "baseName": "exportFile",
            "type": "ExportApplicationRequestExportFile"
        },
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<ExportApplicationRequestDataFunctionsInner>"
        },
        {
            "name": "transactionFunctions",
            "baseName": "transactionFunctions",
            "type": "Array<ExportApplicationRequestTransactionFunctionsInner>"
        }    ];

    static getAttributeTypeMap() {
        return ExportApplicationRequest.attributeTypeMap;
    }
}

export namespace ExportApplicationRequest {
    export enum ProjectTypeEnum {
        NEW = <any> 'N',
        ENHANCEMENT = <any> 'E',
        REDEVELOPMENT = <any> 'R'
    }
    export enum IpaValueTypeEnum {
        MEDIAN = <any> 'M',
        AVERAGE = <any> 'A'
    }
}
