/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CalcTestApplicationRequestDataFunctionsInner } from './calcTestApplicationRequestDataFunctionsInner';
import { CalcTestApplicationRequestProcessRatios } from './calcTestApplicationRequestProcessRatios';
import { CalcTestApplicationRequestTransactionFunctionsInner } from './calcTestApplicationRequestTransactionFunctionsInner';
import { ExportApplicationRequestImportFile } from './exportApplicationRequestImportFile';

/**
* エクスポートリクエスト
*/
export class ExportApplicationRequest {
    'projectName'?: string;
    'productivityFPPerMonth'?: number;
    'projectType'?: string;
    'ipaValueType'?: string;
    'totalFP'?: number;
    'totalManMonths'?: number;
    'standardDurationMonths'?: number;
    'processRatios'?: CalcTestApplicationRequestProcessRatios;
    'processManMonths'?: CalcTestApplicationRequestProcessRatios;
    'processDurations'?: CalcTestApplicationRequestProcessRatios;
    'importFile'?: ExportApplicationRequestImportFile;
    'exportFile'?: ExportApplicationRequestImportFile;
    'dataFunctions'?: Array<CalcTestApplicationRequestDataFunctionsInner>;
    'transactionFunctions'?: Array<CalcTestApplicationRequestTransactionFunctionsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "productivityFPPerMonth",
            "baseName": "productivityFPPerMonth",
            "type": "number"
        },
        {
            "name": "projectType",
            "baseName": "projectType",
            "type": "string"
        },
        {
            "name": "ipaValueType",
            "baseName": "ipaValueType",
            "type": "string"
        },
        {
            "name": "totalFP",
            "baseName": "totalFP",
            "type": "number"
        },
        {
            "name": "totalManMonths",
            "baseName": "totalManMonths",
            "type": "number"
        },
        {
            "name": "standardDurationMonths",
            "baseName": "standardDurationMonths",
            "type": "number"
        },
        {
            "name": "processRatios",
            "baseName": "processRatios",
            "type": "CalcTestApplicationRequestProcessRatios"
        },
        {
            "name": "processManMonths",
            "baseName": "processManMonths",
            "type": "CalcTestApplicationRequestProcessRatios"
        },
        {
            "name": "processDurations",
            "baseName": "processDurations",
            "type": "CalcTestApplicationRequestProcessRatios"
        },
        {
            "name": "importFile",
            "baseName": "importFile",
            "type": "ExportApplicationRequestImportFile"
        },
        {
            "name": "exportFile",
            "baseName": "exportFile",
            "type": "ExportApplicationRequestImportFile"
        },
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<CalcTestApplicationRequestDataFunctionsInner>"
        },
        {
            "name": "transactionFunctions",
            "baseName": "transactionFunctions",
            "type": "Array<CalcTestApplicationRequestTransactionFunctionsInner>"
        }    ];

    static getAttributeTypeMap() {
        return ExportApplicationRequest.attributeTypeMap;
    }
}

