/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExportApplication200ResponseDataFunctionsInner } from './exportApplication200ResponseDataFunctionsInner';
import { ExportApplication200ResponseExportFile } from './exportApplication200ResponseExportFile';

/**
* エクスポートレスポンス
*/
export class ExportApplication200Response {
    'dataFunctions'?: Array<ExportApplication200ResponseDataFunctionsInner>;
    'exportFile'?: ExportApplication200ResponseExportFile;
    'errorMessages'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<ExportApplication200ResponseDataFunctionsInner>"
        },
        {
            "name": "exportFile",
            "baseName": "exportFile",
            "type": "ExportApplication200ResponseExportFile"
        },
        {
            "name": "errorMessages",
            "baseName": "errorMessages",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ExportApplication200Response.attributeTypeMap;
    }
}

