/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CalcTestApplication200ResponseDisplayedProcessRatios } from './calcTestApplication200ResponseDisplayedProcessRatios';
import { CalcTestApplication200ResponseProcessFPs } from './calcTestApplication200ResponseProcessFPs';
import { ExportApplication200ResponseDataFunctionsInner } from './exportApplication200ResponseDataFunctionsInner';
import { ExportApplicationRequestTransactionFunctionsInner } from './exportApplicationRequestTransactionFunctionsInner';
import { ImportApplication200ResponseProcessRatios } from './importApplication200ResponseProcessRatios';

/**
* インポートレスポンス
*/
export class ImportApplication200Response {
    'projectName': string;
    'productivityFPPerMonth': number;
    'projectType': string;
    'ipaValueType': string;
    'totalFP'?: number;
    'totalManMonths'?: number;
    'standardDurationMonths'?: number;
    'processRatios': ImportApplication200ResponseProcessRatios;
    'displayedProcessRatios'?: CalcTestApplication200ResponseDisplayedProcessRatios;
    'processFPs'?: CalcTestApplication200ResponseProcessFPs;
    'processManMonths'?: ImportApplication200ResponseProcessRatios;
    'processDurations'?: ImportApplication200ResponseProcessRatios;
    'dataFunctions'?: Array<ExportApplication200ResponseDataFunctionsInner>;
    'transactionFunctions'?: Array<ExportApplicationRequestTransactionFunctionsInner>;
    'errorMessages'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "productivityFPPerMonth",
            "baseName": "productivityFPPerMonth",
            "type": "number"
        },
        {
            "name": "projectType",
            "baseName": "projectType",
            "type": "string"
        },
        {
            "name": "ipaValueType",
            "baseName": "ipaValueType",
            "type": "string"
        },
        {
            "name": "totalFP",
            "baseName": "totalFP",
            "type": "number"
        },
        {
            "name": "totalManMonths",
            "baseName": "totalManMonths",
            "type": "number"
        },
        {
            "name": "standardDurationMonths",
            "baseName": "standardDurationMonths",
            "type": "number"
        },
        {
            "name": "processRatios",
            "baseName": "processRatios",
            "type": "ImportApplication200ResponseProcessRatios"
        },
        {
            "name": "displayedProcessRatios",
            "baseName": "displayedProcessRatios",
            "type": "CalcTestApplication200ResponseDisplayedProcessRatios"
        },
        {
            "name": "processFPs",
            "baseName": "processFPs",
            "type": "CalcTestApplication200ResponseProcessFPs"
        },
        {
            "name": "processManMonths",
            "baseName": "processManMonths",
            "type": "ImportApplication200ResponseProcessRatios"
        },
        {
            "name": "processDurations",
            "baseName": "processDurations",
            "type": "ImportApplication200ResponseProcessRatios"
        },
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<ExportApplication200ResponseDataFunctionsInner>"
        },
        {
            "name": "transactionFunctions",
            "baseName": "transactionFunctions",
            "type": "Array<ExportApplicationRequestTransactionFunctionsInner>"
        },
        {
            "name": "errorMessages",
            "baseName": "errorMessages",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ImportApplication200Response.attributeTypeMap;
    }
}

