/**
 * 見積算出システム API
 * ...
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CalcTestApplicationRequestProcessRatios } from './calcTestApplicationRequestProcessRatios';
import { CalcTestApplicationRequestTransactionFunctionsInner } from './calcTestApplicationRequestTransactionFunctionsInner';
import { ExportApplication200ResponseDataFunctionsInner } from './exportApplication200ResponseDataFunctionsInner';

/**
* インポートレスポンス
*/
export class ImportApplication200Response {
    'projectName'?: string;
    'productivityFPPerMonth'?: number;
    'projectType'?: string;
    'ipaValueType'?: string;
    'totalFP'?: number;
    'totalManMonths'?: number;
    'standardDurationMonths'?: number;
    'processRatios'?: CalcTestApplicationRequestProcessRatios;
    'processManMonths'?: CalcTestApplicationRequestProcessRatios;
    'processDurations'?: CalcTestApplicationRequestProcessRatios;
    'dataFunctions'?: Array<ExportApplication200ResponseDataFunctionsInner>;
    'transactionFunctions'?: Array<CalcTestApplicationRequestTransactionFunctionsInner>;
    'errorMessages'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "projectName",
            "baseName": "projectName",
            "type": "string"
        },
        {
            "name": "productivityFPPerMonth",
            "baseName": "productivityFPPerMonth",
            "type": "number"
        },
        {
            "name": "projectType",
            "baseName": "projectType",
            "type": "string"
        },
        {
            "name": "ipaValueType",
            "baseName": "ipaValueType",
            "type": "string"
        },
        {
            "name": "totalFP",
            "baseName": "totalFP",
            "type": "number"
        },
        {
            "name": "totalManMonths",
            "baseName": "totalManMonths",
            "type": "number"
        },
        {
            "name": "standardDurationMonths",
            "baseName": "standardDurationMonths",
            "type": "number"
        },
        {
            "name": "processRatios",
            "baseName": "processRatios",
            "type": "CalcTestApplicationRequestProcessRatios"
        },
        {
            "name": "processManMonths",
            "baseName": "processManMonths",
            "type": "CalcTestApplicationRequestProcessRatios"
        },
        {
            "name": "processDurations",
            "baseName": "processDurations",
            "type": "CalcTestApplicationRequestProcessRatios"
        },
        {
            "name": "dataFunctions",
            "baseName": "dataFunctions",
            "type": "Array<ExportApplication200ResponseDataFunctionsInner>"
        },
        {
            "name": "transactionFunctions",
            "baseName": "transactionFunctions",
            "type": "Array<CalcTestApplicationRequestTransactionFunctionsInner>"
        },
        {
            "name": "errorMessages",
            "baseName": "errorMessages",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ImportApplication200Response.attributeTypeMap;
    }
}

